### ISSUE TITLE
Question from newbie modder

### ISSUE THREAD

**Issue by dani-beltran** [RustyMods/VikingNPC#11]
Hi, loving you mod @RustyMods 

I want to collaborate with you on it. For example adding localization to Spanish.

However, I can't build the dll, because some classes are using private methods and variables.
Like the one in this link.

https://github.com/RustyMods/VikingNPC/blob/e0bd14cd54247977a67cc6b5ff035f76440a55d6/Settlers/Behaviors/CompanionAI.cs#L47

UpdateTarget is a private method from MonsterAI class from which your class inherits.
**How do you make this work??**

**Comment by dani-beltran** [comment]
Ok no worries. I found how is done [here](https://github.com/Valheim-Modding/Wiki/wiki/Best-Practices#publicize-the-game-assemblies).

**Comment by RustyMods** [comment]
Let me know if you have any questions - happy to have you make your own version of it or collab.
