### ISSUE TITLE
Tame vikings cant hit wood target

### ISSUE THREAD

**Issue by Onins** [RustyMods/VikingNPC#3]
Right before they attack a tree or stump they rotate during the animation which makes them miss the target

**Comment by Onins** [comment]
https://drive.google.com/file/d/1eqE_6bcIfSmCzuAfcxRL0WpR4vLzfxFb/view?usp=drive_link

**Comment by Onins** [comment]
This also applies to mining

**Comment by RustyMods** [comment]
0.1.0 - lmk if this still an issue

**Comment by Onins** [comment]
@RustyMods thank you for updating the mod

The aim has improvements but sometimes they still miss specially on the stumps. They rotate right before they attack. They also have problems when a tree is diagonally inclined in another tree since they often aim at the middle. Not sure if this is something that can be fixed unless they switch targets if not hitting any for a certain number of swings.

**Comment by Onins** [comment]
https://drive.google.com/file/d/1_YG7r-fvta4K_RiOs27MbjCktJxGEkqJ/view?usp=sharing

**Comment by Onins** [comment]
Is it also possible to add a slider for radius/range for settlers in searching trees and ores? Same as well with follow call.
